package com.evbox.assignment.service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

import com.evbox.assignment.data.dto.ChargeSessionDto;

/**
 * ChargeSessionDto repository
 * Communicates over immutable ChargeSessionDto
 * The data structure to store data is specific to the implementation
 * provide update, add, get, get all and getLast methods
 */
public interface ChargeSessionData {
	
	/**
	 * Updates the session details in the memory with the data provided.
	 * The entity to be updated is matched by id
	 * @param session
	 * @return saved session
	 */
	ChargeSessionDto updateSession(ChargeSessionDto session);
	/**
	 * Adds session details in the memory with the data provided.
	 * Id is generated by the implementation
	 * @param session
	 * @return saved session
	 */
	ChargeSessionDto addSession(ChargeSessionDto session);
	/**
	 * Returns the matching session
	 * @param session Id
	 * @return matching session
	 */
	ChargeSessionDto getSession(UUID id);
	/**
	 * Returns all session information in the memory
	 * @return list of sessions
	 */
	List<ChargeSessionDto> getAll();
	/**
	 * Returns the list of sessions created after the specified time
	 * @param startFrom
	 * @return list of sessions
	 */
	List<ChargeSessionDto> getLastNodes(LocalDateTime startFrom);

}
